import 'package:credynox/frontend/models/automation_event_model.dart';
import 'package:credynox/frontend/widgets/nx_card.dart';
import 'package:credynox/frontend/widgets/nx_pressable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:credynox/core/theme/app_colors.dart';
import 'package:flutter_animate/flutter_animate.dart';

class AutomationTimeline extends StatelessWidget {
  const AutomationTimeline({super.key, required this.automationAsync});

  final AsyncValue<List<AutomationEventModel>> automationAsync;

  @override
  Widget build(BuildContext context) {
    return NxPressable(
      pressScale: 0.94,
      child: NxCard(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const NxCardHeader(
              title: 'AUTOMATION TIMELINE',
              subtitle: 'Dynamic events generated by the engine',
              icon: Icons.timeline_rounded,
              iconColor: AppColors.violet,
            ),
            const SizedBox(height: 18),
            automationAsync.when(
              data: (events) {
                if (events.isEmpty) {
                  return const Text('No automation events yet', style: TextStyle(color: AppColors.textSecondary));
                }
      
                return Container(
                  decoration: BoxDecoration(
                    color: AppColors.bgOverlay,
                    borderRadius: BorderRadius.circular(18),
                    border: Border.all(color: AppColors.borderSubtle),
                  ),
                  child: Column(
                    children: events.take(6).toList().asMap().entries.map((entry) {
                      final index = entry.key;
                      final event = entry.value;
                      final isLast = index == events.take(6).length - 1;
                      return Column(
                        children: [
                          Padding(
                            padding: const EdgeInsets.all(18),
                            child: Row(
                              children: [
                                Container(
                                  width: 10,
                                  height: 10,
                                  decoration: BoxDecoration(
                                    color: event.status.toLowerCase() == 'completed' ? AppColors.emerald : AppColors.amber,
                                    shape: BoxShape.circle,
                                  ),
                                ),
                                const SizedBox(width: 14),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(event.action, style: const TextStyle(color: AppColors.textPrimary, fontWeight: FontWeight.w600)),
                                      const SizedBox(height: 4),
                                      Text(
                                        event.timestamp.toLocal().toIso8601String().substring(0, 19),
                                        style: const TextStyle(color: AppColors.textTertiary, fontSize: 12),
                                      ),
                                    ],
                                  ),
                                ),
                                Text(
                                  event.status.toUpperCase(),
                                  style: TextStyle(
                                    color: event.status.toLowerCase() == 'completed' ? AppColors.emerald : AppColors.amber,
                                    fontSize: 11,
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          if (!isLast) const NxDivider(),
                        ],
                      );
                    }).toList(),
                  ),
                );
              },
              loading: () => const Padding(
                padding: EdgeInsets.all(12),
                child: SizedBox(
                  height: 24,
                  width: 24,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ),
              error: (error, _) => Text('Failed to load timeline: $error', style: const TextStyle(color: Colors.redAccent)),
            ),
          ],
        ),
      ).animate().fadeIn(duration: 300.ms).slideY(begin: 0.08),
    );
  }
}